# Richard Fernando Heise Ferreira (GRR20191053)

CFLAGS  = -g
CC = gcc 

#-----------------------------------------------------------------------------#
all : ConexaoRawSocket

run: ConexaoRawSocket
	sudo ./ConexaoRawSocket

ConexaoRawSocket: ConexaoRawSocket.o


#-----------------------------------------------------------------------------#

clean :
	$(RM) *.o

#-----------------------------------------------------------------------------#

purge:
	$(RM) ConexaoRawSocket *.o